-- schema.sql
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    order_type VARCHAR(50),
    status VARCHAR(50)
);
